### ISSUE TITLE
possible error in PollHandler with handling URIs

### ISSUE THREAD

**Issue by standevgd** [gooddata/gooddata-java#502]
I think [this](https://github.com/gooddata/gooddata-java/commit/59d199eca9abe7042f32c0829ad598308cf404b2#diff-e28f4ead8b59708256cb476e6f5c40d4R50) broke something for us. When I'm trying to run `CreateInstanceAT` in `gdc-datawarehouse` using new `gooddata-java` library, it now results in error:
```
Caused by: org.apache.http.ProtocolException: Target host is not specified
    at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:69)
    at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
```

The reason, I believe is that `pollingUri` is not a full URI, but partial, e.g. `/gdc/workers/create/1234` and does not contain neither protocol, nor host.

When I revert to `2.13.0`, the acceptance test is working fine again.

**Comment by martiner** [comment]
The type changed from String to URI, the content remains the same - it has never been "full URI".

Such URIs are processed by UriPrefixer which enriches them with "prefix" - protocol, hostname, port.

**Comment by standevgd** [comment]
here's the full stacktrace which might help:
```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "/gdc/workers/datawarehouse.create/tasks/d380b6a0-5f2a-42d1-a4b5-badf3a62393e": null; nested exception is org.apache.http.client.ClientProtocolException

	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at com.gooddata.AbstractService.pollOnce(AbstractService.java:75)
	at com.gooddata.AbstractService.poll(AbstractService.java:56)
	at com.gooddata.PollResult.get(PollResult.java:48)
	at com.gooddata.datawarehouse.worker.AbstractAT.executeTask(AbstractAT.java:31)
	at com.gooddata.datawarehouse.worker.CreateInstanceWorkerAT.testCreateInstance(CreateInstanceWorkerAT.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
	... 30 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:70)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
	... 36 more
```

It fails at `PollResult` and `AbstractService.poll`

**Comment by martiner** [comment]
In your code you are using `org.springframework.boot.web.client.RootUriTemplateHandler` instead of `com.gooddata.UriPrefixer`.

Poll URI can't be used as a URI template because of double-encoding problem.

**Comment by standevgd** [comment]
ok thanks for clarification, so it's a problem at our end then which came to surface. Will try to fix it using your suggestion.

**Comment by ostumpf** [comment]
@martiner So the most straightforward way of utilizing `UriPrefixer` is via `UriPrefixingClientHttpRequestFactory`, which however is not public. Would you consider making it public so that we can use in gdc-taskman?
